[project]
name = "koe"
version = "0.4.0"
description = "Another Lavalink connection library for Hikari."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dacite>=1.9.2",
    "hikari[speedups]>=2.5.0",
    "loguru>=0.7.3",
    "orjson>=3.11.4",
    "websockets>=15.0.1",
]
